### ISSUE TITLE
Support Resume from Replay

### ISSUE THREAD

**Issue by GraylinKim** [GraylinKim/sc2reader#91]
Totally failing right now.

**Comment by nibalizer** [comment]
I found this issue with resumed replays. Haven't dug into it much but here is a stacktrace and its pretty obvious what file it blew up on:

```
 (master * u=)$: python sc2analyzer.py '../WCS 2015 Season 1/SSL/Challenge/Roundof32_Classic_Cure_1Set(After Recover).SC2Replay'
Traceback (most recent call last):
  File "sc2analyzer.py", line 48, in <module>
    main()
  File "sc2analyzer.py", line 32, in main
    replay = sc2reader.load_replay(filename, debug=True)
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/factories/sc2factory.py", line 85, in load_replay
    return self.load(Replay, source, options, **new_options)
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/factories/sc2factory.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/factories/sc2factory.py", line 146, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/resources.py", line 309, in __init__
    engine.run(self)
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/engine/engine.py", line 174, in run
    for new_event in (event_handler(event, replay) or []):
  File "/home/nibz/projects/sc2replay_proc/venv/local/lib/python2.7/site-packages/sc2reader/engine/plugins/context.py", line 228, in handleUnitDoneEvent
    self.logger.error("Unit {0} done at {1} [{2}] before it was started!".format(event.killer_pid, Length(seconds=event.second), event.frame))
AttributeError: 'UnitDoneEvent' object has no attribute 'killer_pid'
```
